In [3]:
import numpy as np
import math

# Arrays 

In [4]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
b.shape

(2, 3)

In [7]:
array.dtype

dtype('int32')

In [11]:
c = np.array([2.3,5,1.1])
c.dtype.name

'float64'

In [12]:
c

array([2.3, 5. , 1.1])

In [16]:
#array vacios
d = np.zeros((2,3))
print(d)
e = np.ones((3,5))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
np.random.rand(2,3)

array([[0.19869548, 0.1054865 , 0.53948977],
       [0.00495991, 0.20741826, 0.45777939]])

In [26]:
f = np.arange(10,50, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


# Operaciones con arrays

In [27]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = a-b
print(c)


[ 9 18 27 36]


In [28]:
fd = np.array([0,-10,-5,-15,0])
celcius = (fd -31)*(5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [29]:
celcius > -20

array([ True, False, False, False,  True])

In [30]:
celcius%2 == 0

array([False, False,  True, False, False])

In [31]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [33]:
def a():
    return ["asd", "c", "c"]

print(len(a()))

3
