# Expresiones regulares

In [2]:
import numpy as np

In [10]:
a1 = np.random.rand(4)
a2 = np.random.rand(4,1)
a3 = np.array([[1,2,3,4]])
a4 = np. arange(1,4,1)
a5 = np.linspace(1,4,4)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

import re


[0.94115288 0.09533806 0.61087952 0.05048465]
[[0.49059403]
 [0.64015413]
 [0.57741337]
 [0.29284612]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]


In [14]:
s = "https://google.com https://beidu.com"

print(re.findall("(?<=https:\/\/)([A-Za-z0-9.]*)",s))

['google.com', 'beidu.com']


In [2]:
s = "ACBCAC"
re.findall("AC", s)

NameError: name 're' is not defined

In [6]:
%%timeit -n 100
def fizzbuzz(max):
    for i in range(max):
        if i % 3 == 0: #and i % 5 == 0:
            print(i)
#             print("FizzBuzz")
#         elif i % 3 == 0:
#             print("Fizz")
#         elif i % 5 == 0:
#             print("Buzz")
#         else:
#             print(i)
fizzbuzz(31)

0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15


18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30
0
3
6
9
12
15
18
21
24
27
30

In [8]:
%%timeit -n 100
# def div_by_3(n):
#     if n == 0 or n == 3:
#         return True
#     elif n < 3:
#         return False
    
#     return div_by_3(n - (n&7))


def div_by_3_1(n):
    return 0x9249249249249249249249249249249249249249249249249249249249249249>>n&1

def fizzbuzz(max):
    for i in range(max):
        if(div_by_3_1(i)):
            print(i)
fizzbuzz(30)

0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
1

6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18
21
24
27
0
3
6
9
12
15
18